#!/usr/bin/env bash
#
#       _      _     _                       _       
#    __| | ___| |__ (_) __ _ _ __         __| | ___  
#   / _` |/ _ \ '_ \| |/ _` | '_ \ _____ / _` |/ _ \ 
#  | (_| |  __/ |_) | | (_| | | | |_____| (_| | (_) |
#   \__,_|\___|_.__/|_|\__,_|_| |_|      \__,_|\___/ 
#                                                                   
#
#  *****************************************************
#
# NAME        : debian-do.sh
#
# VERSION     : 0.1
#
# TESTED on   : Debian Jessie 8.7 (amd64) droplet with a selected ssh-key options!!
#
# DESCRIPTION : Quick & dirty minimal security for a new digital-ocean server 
#               - Setup a new "remoteadmin" user with sudo, ssh access on port 2222, and minimum bash color config
#               - disallow root ssh login
#               - Install & update clamav antivirus (custom update & scan need to be added with cron)
#               - Install and configure fail2ban and ufw only for ssh on port 2222
#               
# HOW TO      : 1. Download the script
#               2. ssh root@<IP-SERVER> and type yes
#               3. Open a new term (ctrl T) and copy the script:  scp root@<IP-SERVER>:/root
#               4. on the server : chmod u+x debian.do-sh && ./debian-do.sh (the prompt will ask you a remoteadmin password)
#               5. quit your server with : exit && exit
#!/usr/bin/env bash
#
echo -e "\033[032mUpdating repo\033[0m ..."
sleep 1
apt-get update
echo -e "\033[032mupgrading packages\033[0m ..."
sleep 1
apt-get dist-upgrade -y
echo -e "\033[032mAdding remoteadmin user\033[0m ..."
sleep 1
useradd -m remoteadmin
echo -e "\033[032mAdding sudo to remoteadmin user\033[0m ..." 
sleep 1
adduser remoteadmin sudo
passwd remoteadmin
echo -e "\033[032mSetup ssh key acces for remoteadmin user\033[0m ..."
sleep 1
mkdir /home/remoteadmin/.ssh
cp /root/.ssh/authorized_keys /home/remoteadmin/.ssh/authorized_keys
chown -R remoteadmin:remoteadmin /home/remoteadmin/.ssh/
chmod 700 /home/remoteadmin/.ssh
chmod 600 /home/remoteadmin/.ssh/authorized_keys
echo -e "\033[032mSetup ssh on port 2222 only for remoteadmin user\033[0m ..."
sleep 1
sed -i -e "s/22/2222/g" /etc/ssh/sshd_config
sed -i -e "s/PermitRootLogin yes/PermitRootLogin no\nAllowUsers remoteadmin/g" /etc/ssh/sshd_config
sed -i -e "s/#AuthorizedKeysFile/AuthorizedKeysFile/g" /etc/ssh/sshd_config 2> /dev/null
 # only allow ssh connexions from a vpn ? modify sshd_config with ListenAddress XX.XX.XX.XX
echo -e "\033[032mRestarting ssh service\033[0m ..."
sleep 1
systemctl restart ssh
echo -e "\033[032mSetup bash color prompt for remoteadmin user\033[0m ..."
sleep 1
cp /root/.bashrc /home/remoteadmin/.bashrc
cp /root/.bash_logout /home/remoteadmin/.bash_logout
cp /root/.profile /home/remoteadmin/.profile
sed -i '$ a bash' /home/remoteadmin/.profile
sed -i -e "s/#force_color_prompt=yes/force_color_prompt=yes/g" /home/remoteadmin/.bashrc
source /home/remoteadmin/.bashrc
echo -e "\033[032mInstalling fail2ban\033[0m ..."
sleep 1
apt-get install fail2ban -y
echo -e "\033[032mSetup fail2ban for ssh on port 2222\033[0m ..."
cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
sed -i -e "s/port     = ssh/port     = 2222/g" /etc/fail2ban/jail.local
echo -e "\033[032mActivate fail2ban at startup\033[0m ..."
sleep 1
systemctl enable fail2ban
echo -e "\033[032mRestarting fail2ban service\033[0m ..."
sleep 1
systemctl restart fail2ban
echo -e "\033[032mInstalling clamav antivirus and updating db\033[0m ..."
sleep 1
apt-get install clamav -y
systemctl stop clamav-freshclam
freshclam
systemctl start clamav-freshclam 
clamscan -r -i /home/remoteadmin
#update cron with periodic  manual clamav and fresclam
# or install clamd for autoscan but it needs more memory
echo -e "\033[032mInstalling ufw firewall service\033[0m ..."
sleep 1
apt-get install ufw
echo -e "\033[032mSetup ufw only for ssh access on port 2222\033[0m ..."
ufw allow 2222/tcp
#ufw allow from VPN.IP.X.X to  any port 2222
echo -e "\033[032mActivate ufw rules\033[0m ..."
sleep 1
ufw --force enable
ufw status numbered
echo -e "\033[032mBasic VPS setup terminated\nReboot and list your services with systemctl list-units --type=service\nConnect to your server with ssh remoteadmin@<YOUR-IP> -p 2222\nCustomize your config now\033[0m !"
